apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
  labels:
    app: mango-monitoring-service
  name: mango-monitoring-service
  namespace: default
  resourceVersion: "65918483"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mango-monitoring-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mango-monitoring-service
    spec:
      containers:
      - env:
        - name: NETWORK_NAME
          valueFrom:
            secretKeyRef:
              key: NETWORK_NAME
              name: env-vars
        - name: RPC_URL
          valueFrom:
            secretKeyRef:
              key: RPC_URL
              name: env-vars
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: DIALECT_PRIVATE_KEY
              name: env-vars
        image: dialectlab/mango-monitoring-service:0.1.0
        imagePullPolicy: Always
        name: mango-monitoring-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
